#!/bin/sh
# vim: set ts=4:
#
# Builds standalone luapak binary using Luapak.
#
# Environment variables:
#   LDFLAGS : Extra flags to pass to the linker.
#   LIBC    : System libc library; if "musl" and LDFLAGS is not set, then
#             LDFLAGS is set to "-static -no-pie" (static linking).
set -eu

. "$(dirname "$0")/bootstrap"

einfo 'Building standalone luapak'

if [ "${LIBC:-}" = musl ] && [ -z "${LDFLAGS:-}" ]; then
	export LDFLAGS='-static -no-pie'
fi

rm -Rf "$TEMP_DIR"/* dist/*

# Note: LUA_VERSION interferes with LuaRock's Makefile, so we must unset it.
LUA_VERSION= \
	lua luapak/cli/init.lua make -v -t "$TEMP_DIR"
printf '\n'

run ls -lh dist/luapak
run file dist/luapak

case "$HOST_OS" in
	Darwin) run otool -L dist/luapak;;
	Linux) run ldd dist/luapak || true;;
esac

run ./dist/luapak --version
