#!/bin/sh
# vim: set ts=4:
#
# This script is run on CI to prepare build environment.
#
# Environment variables:
#   TARGET_ARCH : Target architecture (others than x86_64 are emulated using QEMU).
#
set -eu

cd "$(dirname "$0")/.."
. script/utils.sh

[ "$HOST_OS" = Linux ] || exit 0

einfo 'Downloading alpine-chroot-install'
wgets 'https://raw.githubusercontent.com/alpinelinux/alpine-chroot-install/v0.5.0/alpine-chroot-install' \
	'936abfd1906c77418b03528c0b84cc81023cb4d0529468f3861c3aad198a0d3d'

sudo sh alpine-chroot-install \
	-a "$TARGET_ARCH" -b v3.6 -k 'LIBC LUA_VERSION TARGET_ARCH' \
	-p 'build-base curl file git python wget'
