#!/bin/sh
# vim: set ts=4:
#
# Runs tests and linters.
#
set -eu

. "$(dirname "$0")/bootstrap"

einfo 'Running linters'

luacheck $PKG_NAME/*

for rockspec in *.rockspec; do
	luarocks lint "$rockspec"
done
